name: whisper_ffi
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/Piero512/whisper_ffi


environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  # path: ^1.8.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
